config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "articles#index"
  
  # get "articles", to: "articles#index"
  # get "articles/:id", to: "articles#show"
  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    include Visible

    has_many :comments, dependent: :destroy
    has_rich_text :content

    validates_presence_of :title, on: :create, message: "Couldn't be empty"
    # validates_presence_of :body, on: :create, message: "No puede estar vacio"
    # validates :body, length: {minimum:2, too_short: "Se requieren al menos de 2 caracteres"}
 
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  
  belongs_to :article  
end

app/models/concerns/visible.rb
module Visible 
    extend ActiveSupport::Concern

    VALID_STATUSES = [ 'public', 'private', 'archived' ]

    included do
        validates :status, inclusion: { in: VALID_STATUSES }
    end

    class_methods do
        def public_count
            where(status: 'public').count
        end
    end
    # Instanced Objects methods
    def archived?
        status == 'archived'
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new  
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = "Successfuly created"
      redirect_to @article
    else
      flash[:error] = "Something was wrong"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
     end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end  
  end

  def destroy
    @article.destroy 
    redirect_to articles_path, status: :see_other
    #redirect_back(fallback_location: articles_path)
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :content, :status)
    end
      
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_article

    def create
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end

    def destroy
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        puts "si entro al controlador y destruyo el cometario"
        redirect_to article_path(@article), status: 303
    end

    private
        def set_article
            @article = Article.find(params[:article_id])
        end

        def comment_params
            params.require(:comment).permit(:commenter, :body, :status)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_controller?(controller)
        params[:controller]==controller
    end
    def nav_class_for_controller(controller)
        params[:controller] == controller ? " active" : ""
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/active_storage/blobs/_blob.html.slim
| <figure class="attachment attachment--
= blob.representable? ? "preview" : "file"
|  attachment--
= blob.filename.extension
| "> 
- if blob.representable?
  = image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ])
figcaption.attachment__caption
  - if caption = blob.try(:caption)
    = caption
  - else
    span.attachment__name
      = blob.filename
    span.attachment__size
      = number_to_human_size blob.byte_size

app/views/articles/_form.html.slim
/ = form_with model: article do |form|
/     - if article.errors.any?
/         div style="color: red">
/             h2
/                 = pluralize(person.errors.count, "error")
/             ul
/                 - article.errors.each do |error|
/                     li
/                         = error.full_message
/     div
/         = form.label :title, style: "display: block"
/         = form.text_field :title

/     div
/         = form.label :content, style: "display: block"
/         = form.rich_text_area :content

/     div 
/         = form.label :status, style: "display: block"
/         = form.select :status, ['public', 'private', 'archived'], selected: 'public'
/     div
/         = form.submit class: "btn btn-primary me-1"
/         = link_to "Cancel", @article, class: "btn btn-outline-primary"


= simple_form_for @article do |f|
    =<> f.input :title
    = f.rich_text_area :content
    = f.input :status, collection: ['public', 'private', 'archived'],\
        selected: 'public', input_html: { class: 'form-select mb-3'}
    = f.submit class: "btn btn-primary me-1"
    = link_to "Cancel", @article, class: "btn btn-outline-primary"

app/views/articles/edit.html.slim
.card.shadow
    .card-header
        h1.card-title 
            p Edit article
    .card-body    
        = render "form", article: @article

app/views/articles/index.html.slim
.card.shadow
  .card-body
    h1.card-title
      p Articles
    p 
      = "This Blog has " + Article.public_count.to_s + " public articles"
    div id="articles"
      table.table.table-striped.table-hover
        thead
          tr
            th
              = " Title "
        tbody
          - @articles.each do |article|
            tr 
              td 
                - unless article.archived?
                  =  article.title
              td 
                => link_to "Show", article, class: "btn btn-success"
                => link_to "Edit", edit_article_path(article), class: "btn btn-warning"
                = link_to "Delete", article, class: "btn btn-danger", \
                                    method: :delete, \
                                    data: { "turbo-method": :delete, \
                                    turbo_confirm: "Are you sure?" }

app/views/articles/new.html.slim
.card.shadow
    .card-header
        h1.card-title 
            p New Article
    .card-body
        = render "form", article: @article
               

app/views/articles/show.html.slim
.card.shadow
    .card-header
        h1
            = @article.title
    .card-body
        .card-title
        .card-text.mb-2
            == @article.content
        div.mb-4
            = link_to "Edit", edit_article_path(@article), class: "btn btn-warning me-1"
            = link_to "Delete", article_path(@article), data: { \
                turbo_method: :delete, \
                turbo_confirm: "Are you sure to destroy this article?" },\
                class: "btn btn-danger"
        .card.shadow.mb-2
            .card-body
                .card-title
                    h2 Comentaries
                .blockquote.mb-0
                    = render @article.comments
        .card.shadow.mb-2
            .card-body
                .card-title
                    h2 Add a comment
                = render 'comments/form'

app/views/comments/_comment.html.slim
- unless comment.archived?
    p.fw-bold
        = comment.commenter
    p
        = comment.body

    = link_to "Delete comment", [comment.article, comment], data:{ \
        turbo_method: :delete, \
        turbo_confirm: "Are you sure to delete comment?" }, \
        class: "btn btn-outline-danger"

app/views/comments/_form.html.slim
= simple_form_for [ @article, @article.comments.build ] do |f|
    = f.input :commenter
    = f.input :body
    = f.input :status, collection: ['public', 'private', 'archived'],\
        selected: 'public', input_html: { class: 'form-select mb-3'}
    = f.submit class: "btn btn-primary me-1"

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  div.container-fluid
    = link_to "Home", root_path , class: "navbar-brand"
    button.navbar-toggler type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" 
      span.navbar-toggler-icon
    .collapse.navbar-collapse
      ul.navbar-nav
        li.nav-item
          = link_to "Articles", :articles , class: "nav-link" + nav_class_for_controller('articles')
        li.nav-item
          = link_to "Link 2", "#" , class: "nav-link" + nav_class_for_controller('model') 
        li.nav-item
          = link_to "Link 3", "#" , class: "nav-link" + nav_class_for_controller('anotherModel')

app/views/layouts/action_text/contents/_content.html.slim
.trix-content
  = yield

app/views/layouts/application.html.slim
html
  head
    title
      RailsTutoBlog
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body.bg-light.bg-gradient
    = render "layouts/navigation"
    .container
      = yield
    footer